opi:
  # set ingress endoint when 'use_registry_ingress' is set to true
  ingress_endpoint: no-ingress-set
  use_registry_ingress: false
  use_docker: false

  namespace: eirini
  version: 0.0.0
  init_image: nimak/opi-init
  image: nimak/opi
  image_tag: latest
  rootfs_version: 24.0.0
  rootfs_tag: v24.0.0
  rootfs_patcher_timeout: -1ns
  stager:
    downloader_image: eirini/recipe-downloader
    downloader_image_tag: latest
    executor_image: eirini/recipe-executor
    executor_image_tag: latest
    uploader_image: eirini/recipe-uploader
    uploader_image_tag: latest
kube:
  external_ips: []

scf:
  version: 2.14.5
  secrets_generation_counter: 1

services:
  loadbalanced: false

secrets:
  BITS_SERVICE_SECRET: secret
  BITS_SERVICE_SIGNING_USER_PASSWORD: notpassword123
  BLOBSTORE_PASSWORD:  blobstore

env:
  # Base domain of the SCF cluster.
  # Example: "my-scf-cluster.com"
  DOMAIN: ~

